[06:34:45-646196]A00160028520180213KR4165N30007000001KRDRVFUBM3 K165N30003년국채    F 201803                                                             F 201803                                KTB3       F 201803                                                             F 201803                                2017092020180321 CX001 000000010908 000000010586 000000000000 000000000000 000000000000 000000000000000000010747BM3                           20180320201803210012018032000000000000000000N1000000000000000000000010000000000000003000000000000              000000010772000003600000000000000000111 00000000000000000Y000000000000000002000000010761000000000010761000000000010747000000N000000000000000000000000000000000000000000N000000000000000 0000000107471 000000010755 000000010756 000000010747201711291533479811 0000000013000000233870 000000010748 0000000107470000000000 000000010830 000000010725 000000010802 00000001072520171201201801302018010320180130000003650000000800000030000000000000262100000005418100000000058256083900000000000541810000000005825608390000001650000000000000000B00100000500000007000070000100007NN0000000000000000000000000000000000NY 000000000053-000000000053                     



[09:03:01-204059]G7016KR4175N20007079G1 0010810000000140090301190000000000000000 00108150 00108230 00108100 0010811000054080000584893110000000000000000010003141 00108100000529 00108090000107 00108080000185 00108070000059 001080600001470002292 00108110000071 00108120000286 00108130000276 00108140000070 0010815000024300267002300140012000800110026100080018001600110019 00109180 00107020

In [264]:
a = '[09:03:01-204059]G7016KR4175N20007079G1 0010810000000140090301190000000000000000 00108150 00108230 00108100 0010811000054080000584893110000000000000000010003141 00108100000529 00108090000107 00108080000185 00108070000059 001080600001470002292 '
print(len(a))
b = '[09:03:01-204059]G7016KR4175N20007079G1 0010810000000140090301190000000000000000 00108150 00108230 00108100 0010811000054080000584893110000000000000000010003141 00108100000529 00108090000107 00108080000185 00108070000059 001080600001470002292 00108110000071 00108120000286 00108130000276 00108140000070 0010815000024300267002300140012000800110026100080018001600110019 00109180 00107020'
b[161:169]

243

'00108100'

In [269]:
## 현재 인코딩 문제로 한글인식에 문제가 있음.

# -*- coding: cp949 -*-
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

i=0
s=[]

with open("D:/FinanceData_raw/raw_data_set/sise2local.ALL_CMDT.0213", "rt", encoding='iso-8859-1') as f:
    for i in range(10):
        t = f.readline()[17:]
        print(i, "번째 정보 : ", t[0:5],t[408:411],t[454:457])
        if t[0:5]=='A0016' and t[408:411]=='BM3' and t[454:457]=='001':
            product_ID = t[18:30]
            print('product_ID = ',product_ID)
            break
    for _ in range(20000):
        s.append(f.readline())
    
#조건에 충족하는 틱만 골라내기
ls1 = [i for i in s if (product_ID == i[22:34]) and (i[17:22] == 'A3016' or i[17:22] == 'G7016' )]

print(ls1[5][251:259])

#index별로 자료 
#순서 : 체결시각, 현재가격, 체결수량, 매도1호가, 매수1호가, 최종매도매수, 총잔량매도, 총잔량매수
ls2 = [[row[:17],int(row[40:48]),int(row[48:54]),row[243:251],row[161:169],row[152:153],row[235:242],row[153:160]]for row in ls1]


# print(ls2)

result = pd.DataFrame(ls2,columns=["체결시각", "현재가격", "체결수량","매도1호가","매수1호가", "최종매도매수", "총잔량매도", "총잔량매수"])

result

result.to_csv(str(product_ID)+"_"+str(t[10:18])+".csv", index=False)

0 번째 정보 :  A0016 BM3 001
product_ID =  KR4165N30007
000934 0

,체결시각,현재가격,체결수량,매도1호가,매수1호가,최종매도매수,총잔량매도,총잔량매수
0,[09:00:00-023432],10751,1482,,8 000105,,,000109
1,[09:00:01-262608],10752,15,00010752,00010751,2,0009056,0013628
2,[09:00:01-272302],10752,100,00010752,00010751,2,0008956,0013628
3,[09:00:09-066987],10751,10,00010752,00010751,1,0009539,0013668
4,[09:00:09-745557],10751,55,00010752,00010751,1,0009549,0013613
5,[09:00:10-143275],10751,6,00010752,00010751,1,0009549,0013607
6,[09:00:10-145370],10751,6,00010752,00010751,1,0009549,0013601
7,[09:00:14-694586],10751,2,00010752,00010751,1,0010059,0013855
8,[09:00:17-991845],10751,25,00010752,00010751,1,0010079,0013729
9,[09:00:17-994413],10751,25,00010752,00010751,1,0010079,0013704
10,[09:00:17-994853],10751,25,00010752,00010751,1,0010079,0013679
11,[09:00:17-998958],10751,50,00010752,00010751,1,0010079,0013629
12,[09:00:17-999804],10751,100,00010752,00010751,1,0010079,0013529
13,[09:00:18-001817],10751,9,00010752,00010750,1,0010079,0013520
14,[09:00:18-013067],10751,1,,4 000106,2,,000108
15,[09:00:18-476237],10751,4,00010752,00010751,1,0010068,0013436
16,[09:00:18-478435],10751,4,00010752,00010751,1,0010068,0013432
17,[09:00:18-644843],10751,20,00010752,00010751,1,0010068,0013515
18,[09:00:19-913264],10751,40,00010752,00010751,1,0010101,0013538
19,[09:00:21-496390],10751,10,00010752,00010751,1,0010101,0013578
20,[09:00:22-373330],10751,11,00010752,00010751,1,0010101,0013589
21,[09:00:29-379072],10751,6,00010752,00010751,1,0010124,0013246
22,[09:00:29-383767],10751,6,00010752,00010751,1,0010124,0013237
23,[09:00:31-426485],10751,2,00010752,00010751,1,0010126,0013245
24,[09:00:36-382651],10751,1,00010752,00010751,1,0010126,0013244
25,[09:00:36-387846],10751,1,00010752,00010751,1,0010126,0013243
26,[09:00:39-080919],10751,30,00010752,00010751,1,0010221,0013213
27,[09:00:39-663851],10751,50,00010752,00010751,1,0010221,0013163
28,[09:00:40-130187],10751,6,00010752,00010751,1,0010221,0013107
29,[09:00:42-918300],10751,6,00010752,00010751,1,0010221,0013101
...,...,...,...,...,...,...,...,...
111,[09:06:49-507611],10753,1,00010754,00010753,1,0009964,0015846
112,[09:06:58-858948],10753,100,00010754,00010753,1,0010144,0015713
113,[09:07:04-441438],10753,1,00010754,00010753,1,0010193,0015733
114,[09:07:06-447924],10753,5,00010754,00010753,1,0010194,0015728
115,[09:07:07-874519],10753,50,00010754,00010753,1,0010144,0015678
116,[09:07:08-836974],10753,150,00010754,00010753,1,0010145,0015528
117,[09:07:08-926186],10753,13,00010754,00010753,1,0010145,0015515
118,[09:07:08-926701],10753,100,00010754,00010753,1,0010145,0015415
119,[09:07:08-969924],10753,1,00010754,00010753,1,0010145,0015414
120,[09:07:08-970342],10753,2,00010754,00010753,1,0010145,0015412
121,[09:07:08-971565],10753,1,00010754,00010753,1,0010145,0015411
122,[09:07:08-973126],10753,7,00010754,00010753,1,0010145,0015404
123,[09:07:08-974592],10753,12,00010754,00010753,1,0010145,0015392
124,[09:07:08-977403],10753,1,00010754,00010753,1,0010145,0015391
125,[09:07:08-978903],10753,1,00010754,00010753,1,0010145,0015390
126,[09:07:08-980608],10753,12,00010754,00010753,1,0010145,0015378
127,[09:07:08-981707],10753,25,00010754,00010753,1,0010145,0015353
128,[09:07:09-011686],10753,142,00010754,00010753,1,0010145,0015211
129,[09:07:09-015557],10753,1,00010754,00010753,1,0010145,0015210
130,[09:07:09-052308],10753,2,00010754,00010753,1,0010145,0015208
131,[09:07:09-053581],10753,6,00010754,00010753,1,0010145,0015202
132,[09:07:09-054507],10753,1,00010754,00010753,1,0010145,0015201
133,[09:07:09-056311],10753,5,00010754,00010753,1,0010145,0015196
134,[09:07:09-057341],10753,68,,6 000107,1,,000108
135,[09:07:09-082081],10753,2,00010753,00010752,2,0010240,0015219
136,[09:07:09-099964],10753,1,00010754,00010753,2,0010145,0015227
137,[09:07:09-122564],10753,4,,6 000107,1,,000108
138,[09:07:09-630543],10753,8,00010753,00010752,2,0010159,0015219
139,[09:07:09-633983],10753,10,00010753,00010752,2,0010149,0015219
140,[09:07:28-801806],10752,1,00010753,00010752,1,0010375,0015185