[06:34:45-646196]A00160028520180213KR4165N30007000001KRDRVFUBM3 K165N30003년국채    F 201803                                                             F 201803                                KTB3       F 201803                                                             F 201803                                2017092020180321 CX001 000000010908 000000010586 000000000000 000000000000 000000000000 000000000000000000010747BM3                           20180320201803210012018032000000000000000000N1000000000000000000000010000000000000003000000000000              000000010772000003600000000000000000111 00000000000000000Y000000000000000002000000010761000000000010761000000000010747000000N000000000000000000000000000000000000000000N000000000000000 0000000107471 000000010755 000000010756 000000010747201711291533479811 0000000013000000233870 000000010748 0000000107470000000000 000000010830 000000010725 000000010802 00000001072520171201201801302018010320180130000003650000000800000030000000000000262100000005418100000000058256083900000000000541810000000005825608390000001650000000000000000B00100000500000007000070000100007NN0000000000000000000000000000000000NY 000000000053-000000000053                     



[09:03:01-204059]G7016KR4175N20007079G1 0010810000000140090301190000000000000000 00108150 00108230 00108100 0010811000054080000584893110000000000000000010003141 00108100000529 00108090000107 00108080000185 00108070000059 001080600001470002292 00108110000071 00108120000286 00108130000276 00108140000070 0010815000024300267002300140012000800110026100080018001600110019 00109180 00107020

In [264]:
a = '[09:03:01-204059]G7016KR4175N20007079G1 0010810000000140090301190000000000000000 00108150 00108230 00108100 0010811000054080000584893110000000000000000010003141 00108100000529 00108090000107 00108080000185 00108070000059 001080600001470002292 '
print(len(a))
b = '[09:03:01-204059]G7016KR4175N20007079G1 0010810000000140090301190000000000000000 00108150 00108230 00108100 0010811000054080000584893110000000000000000010003141 00108100000529 00108090000107 00108080000185 00108070000059 001080600001470002292 00108110000071 00108120000286 00108130000276 00108140000070 0010815000024300267002300140012000800110026100080018001600110019 00109180 00107020'
b[161:169]

243

'00108100'

In [282]:
## 현재 사용되는 자료의 인코딩 문제로 한글표현이 잘 안됨.(패킷이 정확한 길이로 나뉘어야되서 특수한 인코딩을 사용하는듯 보임)

%matplotlib inline
#주피터노트북에서 라인 아래에 보여지도록 설정

%config InlineBackend.figure_formats = {'png','retina'} 
#png 이미지 압축기술설정, retina 그래프 해상도 2배 높히기

# -*- coding: cp949 -*-
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s=[]

with open("D:/FinanceData_raw/raw_data_set/sise2local.ALL_CMDT.0213", "rt", encoding='iso-8859-1') as f:
    for i in range(1000):
        t = f.readline()[17:]
        print(i, "번째 정보 : ", t[0:5],t[408:411],t[454:457])
        if t[0:5]=='A0016' and t[408:411]=='BM3' and t[454:457]=='001':
            product_ID = t[18:30]
            print('product_ID = ',product_ID)
            break
    s = f.readlines()
    
#조건에 충족하는 틱정보만 골라내기
ls1 = [i for i in s if (product_ID == i[22:34]) and (i[17:22] == 'A3016' or i[17:22] == 'G7016' )]

#index별로 자료 선택취합
#순서 : 체결시각, 현재가격, 체결수량, 매도1호가, 매수1호가, 최종매도매수, 총잔량매도, 총잔량매수
ls2 = [[row[:17],int(row[40:48]),int(row[48:54]),row[243:251],row[161:169],row[152:153],row[235:242],row[153:160]]for row in ls1]


result = pd.DataFrame(ls2,columns=["체결시각","현재가격","체결수량","매도1호가","매수1호가","최종매도매수","총잔량매도","총잔량매수"])


# plt.plot(result)
# plt.show()

result.to_csv(str(product_ID)+"_"+str(t[10:18])+".csv", index=False)

result

0 번째 정보 :  A0016 BM3 001
product_ID =  KR4165N30007

,체결시각,현재가격,체결수량,매도1호가,매수1호가,최종매도매수,총잔량매도,총잔량매수
0,[09:00:00-023432],10751,1482,,8 000105,,,000109
1,[09:00:01-262608],10752,15,00010752,00010751,2,0009056,0013628
2,[09:00:01-272302],10752,100,00010752,00010751,2,0008956,0013628
3,[09:00:09-066987],10751,10,00010752,00010751,1,0009539,0013668
4,[09:00:09-745557],10751,55,00010752,00010751,1,0009549,0013613
5,[09:00:10-143275],10751,6,00010752,00010751,1,0009549,0013607
6,[09:00:10-145370],10751,6,00010752,00010751,1,0009549,0013601
7,[09:00:14-694586],10751,2,00010752,00010751,1,0010059,0013855
8,[09:00:17-991845],10751,25,00010752,00010751,1,0010079,0013729
9,[09:00:17-994413],10751,25,00010752,00010751,1,0010079,0013704
10,[09:00:17-994853],10751,25,00010752,00010751,1,0010079,0013679
11,[09:00:17-998958],10751,50,00010752,00010751,1,0010079,0013629
12,[09:00:17-999804],10751,100,00010752,00010751,1,0010079,0013529
13,[09:00:18-001817],10751,9,00010752,00010750,1,0010079,0013520
14,[09:00:18-013067],10751,1,,4 000106,2,,000108
15,[09:00:18-476237],10751,4,00010752,00010751,1,0010068,0013436
16,[09:00:18-478435],10751,4,00010752,00010751,1,0010068,0013432
17,[09:00:18-644843],10751,20,00010752,00010751,1,0010068,0013515
18,[09:00:19-913264],10751,40,00010752,00010751,1,0010101,0013538
19,[09:00:21-496390],10751,10,00010752,00010751,1,0010101,0013578
20,[09:00:22-373330],10751,11,00010752,00010751,1,0010101,0013589
21,[09:00:29-379072],10751,6,00010752,00010751,1,0010124,0013246
22,[09:00:29-383767],10751,6,00010752,00010751,1,0010124,0013237
23,[09:00:31-426485],10751,2,00010752,00010751,1,0010126,0013245
24,[09:00:36-382651],10751,1,00010752,00010751,1,0010126,0013244
25,[09:00:36-387846],10751,1,00010752,00010751,1,0010126,0013243
26,[09:00:39-080919],10751,30,00010752,00010751,1,0010221,0013213
27,[09:00:39-663851],10751,50,00010752,00010751,1,0010221,0013163
28,[09:00:40-130187],10751,6,00010752,00010751,1,0010221,0013107
29,[09:00:42-918300],10751,6,00010752,00010751,1,0010221,0013101
...,...,...,...,...,...,...,...,...
1826,[15:33:32-607302],10759,105,00010760,00010759,1,0009139,0019958
1827,[15:33:44-770344],10760,1,00010760,00010759,2,0010398,0019931
1828,[15:33:52-146974],10759,20,00010760,00010759,1,0010398,0019711
1829,[15:33:54-098266],10760,1,00010760,00010759,2,0010397,0019711
1830,[15:33:57-157748],10760,2,00010760,00010759,2,0010495,0019511
1831,[15:33:59-922926],10759,1,00010760,00010759,1,0010495,0019538
1832,[15:34:02-566389],10760,1,00010760,00010759,2,0010704,0019546
1833,[15:34:02-689024],10759,10,00010760,00010759,1,0010794,0019536
1834,[15:34:02-803769],10760,1,00010760,00010759,2,0010793,0019536
1835,[15:34:03-418205],10760,1,00010760,00010759,2,0010792,0019536
1836,[15:34:03-640065],10760,1,00010760,00010759,2,0010791,0019536
1837,[15:34:04-379396],10760,1,00010760,00010759,2,0010790,0019536
1838,[15:34:04-898186],10760,1,00010760,00010759,2,0010789,0019536
1839,[15:34:05-343704],10760,1,00010760,00010759,2,0010788,0019536
1840,[15:34:06-025712],10760,1,00010760,00010759,2,0010787,0019536
1841,[15:34:18-911380],10760,2,00010760,00010759,2,0010885,0019346
1842,[15:34:33-659848],10759,10,00010760,00010759,1,0011075,0019336
1843,[15:34:35-674445],10759,82,00010760,00010759,1,0011075,0019254
1844,[15:34:36-968647],10759,100,00010760,00010759,1,0011075,0019154
1845,[15:34:37-851576],10759,50,00010760,00010759,1,0011075,0019104
1846,[15:34:47-125709],10759,100,00010760,00010759,1,0010945,0019004
1847,[15:34:54-393140],10759,2,00010760,00010759,1,0010955,0018984
1848,[15:34:58-673553],10759,100,00010760,00010759,1,0010955,0018634
1849,[15:34:58-796113],10759,10,00010760,00010759,1,0010955,0018624
1850,[15:34:58-809463],10759,10,00010760,00010759,1,0010955,0018614
1851,[15:34:58-932177],10759,10,00010760,00010759,1,0010955,0018604
1852,[15:34:59-068336],10759,10,00010760,00010759,1,0010955,0018594
1853,[15:34:59-152456],10759,5,00010759,00010758,1,0010950,0018589
1854,[15:34:59-927168],10759,6,00010759,00010758,2,0010998,0018589
1855,[15:45:00-122043],10760,5266,,8 000105,,,000109